### PR TITLE
Updated Analysis.py,  Unit tests, TESTS.md and README.md

### PR DESCRIPTION
**Pull request by faezahari**

### CODE REVIEW

**Comment by mschumak** [comment]
I'll start with README.md:
I like the description and the usage instructions. For installation, the assignment says that they want to install the package directly from Github:
`pip install git+analytic-alchemists/alchemistpkg`

I think step Installation step 4 should be to download the configs folder to the user's working directory.
For usage step 4, explain that plot_data can have a file name argument: plot_data("filename.jpg")
or the path from the configuration file if not specified.

**Comment by mschumak** [comment]
For TESTS.md:
The assignment says that the way they will test our code is:
"We should be able to use your package by running the following code on Colab."
!pip install git+https://github.com/user/yourteamrepo
from yourteamrepo import Analysis

analysis_obj = Analysis.Analysis('config.yml')
analysis_obj.load_data()

analysis_output = analysis_obj.compute_analysis()
print(analysis_output)

analysis_figure = analysis_obj.plot_data()
So, could you change the first test to this code?

**Comment by mschumak** [comment]
I like the addition of the if __name__ == "__main__": clause in Analysis.py.
For the unit tests, we were shown how to use the pytest package. Is the unittest package better?
How was the image.png file created?

**Comment by faezahari** [comment]
For the unit test, both 'unittest' and 'pytest' are testing framework. I
can change 'unitest' to 'pytest' package.

For the image.png, I got as below:
[image: image.png]

**Comment by milanbhakta** [comment]
@faezahari great work just wanted to make a suggestion for load_data tests I think it would be better to use mock data to test it as **calling load_data directly in tests will make 100 requests which will take 25 to 30 minute to just complete one test,** and if its called multiple times in different tests it might reach **rate limit** before passing all test.

**Comment by mschumak** [comment]
I'm going to resolve the merge conflict and merge this into a branch called 'dev' so that we can work on individual files in separate pull requests. Regarding testing, yes, for compute_analysis and plot_data, the input should be fake data that does not require access to the NYT API.

**Pull request merged**
